### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by std-microblock** [std-microblock/blook#1]
- [x] Magic aheadlib loader
- [x] CreateRemoteThread injector
- [x] Process memory api [aob scanner/xtd]
- [x] xref scanner
- [x] assembly injection API
- [x] x86_32 support (half done)
- [ ] Linux/Mac support
- [ ] DRY hook by deducing this
